### ISSUE TITLE
Stream + Projection + Multiple projects / `AndAlso()` is not part of query object in OnBeforeQuery handler

### ISSUE THREAD

**Issue by mcrio** [ravendb/ravendb#12472]
Hi,

This is a strange issue that happens in a specific case when we have two projects where the `OnBeforeQuery` handler is defined in ProjectA while the Stream+Projection query is defined in ProjectB.

The issue is about `AndAlso()` not being part of the query object in `OnBeforeQuery` handler.

When everything is part of the same project there are no issues. Also, the issue occurs only when a **projection** is used on the streamed query.

You can find a test project with failing tests here: https://github.com/mcrio/RavenDbStreamProjectionTest

**Comment by ayende** [comment]
Hi,
There was a recent issue (https://issues.hibernatingrhinos.com/issue/RavenDB-16607) where we didn't apply `OnBeforeQuery` to streaming queries.
That has been resolved, can you test with the latest version?

**Comment by mcrio** [comment]
Hi Oren, yeah I filed that one : ) The test project uses v5.2.1 which is the latest version where that issue is resolved.
Failing test can be found here: https://github.com/mcrio/RavenDbStreamProjectionTest

**Comment by mcrio** [comment]
btw, anyone cloning the test repo please let me know in case the failing test is not reproducible on your end.

**Comment by ayende** [comment]
Sorry for the time to answer, but it was quite complex to narrow it down.
In short, this has to do with dynamic name resolution from the perspective of the C# lang.
You are using the context of the assembly you are building, and that results in different visibility rules applied.
There _should_ be no such problem, since all the types are public, but it still persists.

To work around this, you can use:

```
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Lib")]
```

In the `StreamProjectionTest` project, and then it will work.

🤷

**Comment by mcrio** [comment]
>> Sorry for the time to answer, but it was quite complex to narrow it down.

I can imagine. I needed a day to isolate the problem and make a failing test.

From what you wrote it seems like a .NET bug that could be reported?

**Comment by ayende** [comment]
Yes, that might be a good idea. The problem is that this is so hard to narrow down.
Pretty sure that this is related to the _number_ of assemblies involved, etc.

**Comment by ppekrol** [comment]
Fixed here: https://github.com/ravendb/ravendb/pull/12104

**Comment by mcrio** [comment]
Hi @ppekrol This issue is different. As @ayende explained it has more to do with a .net bug. Not sure if you want to keep it around or document it. I lost about a day producing a failing test, so hopefully, others won't need to do this as well.
